version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "10248:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "18080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=nas.bevis.me
